S3_REGION_NAME = u"eu-central-1"

S3_INPUT_BUCKET_NAME = u"flim-ai-sagemaker"

S3_OUPUT_BUCKET_NAME = u"flim-ai-sagemaker-midgar"
S3_OUPUT_ZIP_NAME = u"_zip"
S3_OUPUT_RESCALED_NAME = u"midgar_divided_rescale"
S3_OUPUT_DIVIDED_NAME = u"midgar_simple_rescale"
S3_OUPUT_THUMBNAILED_NAME = u"midgar_thumbnail"

LOCAL_INPUT_CLASSES = u"data/dataset_movie.csv"

LOCAL_INPUT_HEADER_ID = u"ID"
LOCAL_INPUT_HEADER_TITLE = u"movie"
LOCAL_INPUT_HEADER_DIRECTOR = u"author"
LOCAL_INPUT_HEADER_CLASS = u"Class"
LOCAL_INPUT_HEADER_TIMESTAMP = u"movietime"

S3_INPUT_DIRECTORIES_NAMES = [
    "1949_Bergman_-_Fangelse",
    "1950_Bergman_-_Till_gladje",
    "1950_Fellini_-_Luci_del_varieta",
    "1951_Bergman_-_Sommarlek",
    "1952_Bergman_-_Kvinnors_vantan",
    "1952_Fellini_-_Lo_Sceicco_Bianco",
    "1953_Antonioni_-_I_vinti",
    "1953_Antonioni_-_La_signora_senza_camelie",
    "1953_Bergman_-_Gycklarnas_afton",
    "1953_Fellini_-_I_Vitelloni",
    "1954_Fellini_-_La_strada",
    "1955_Antonioni_-_Le_amiche",
    "1955_Bergman_-_Kvinnordrom",
    "1955_Fellini_-_Il_Bidone",
    "1957_Antonioni_-_Il_grido",
    "1957_Bergman_-_Smultronstallet",
    "1958_Bergman_-_Ansiktet",
    "1958_Bergman_-_Nara_livet",
    "1960_Antonioni_-_L_avventura",
    "1960_Bergman_-_Djavulens_oga",
    "1960_Bergman_-_Jungfrukallan",
    "1960_Fellini_-_La_Dolce_Vita",
    "1960_Godard_-_A_bout_de_souffle",
    "1960_Godard_-_Le_Petit_Soldat",
    "1961_Antonioni_-_L_eclisse",
    "1961_Bergman_-_Sasom_i_en_spegel",
    "1962_Antonioni_-_La_notte",
    "1962_Godard_-_Vivre_Sa_Vie",
    "1963_Bergman_-_Nattvardsgasterna",
    "1963_Bergman_-_Tystnaden",
    "1963_Fellini_-_Otto_e_mezzo",
    "1963_Godard_-_Le_Mepris",
    "1963_Godard_-_Les_Carabiniers",
    "1964_Antonioni_-_Il_deserto_rosso",
    "1964_Godard_-_Bande_a_part",
    "1964_Godard_-_Une_Femme_Mariee",
    "1965_Godard_-_Alphaville",
    "1965_Godard_-_Pierrot_le_fou",
    "1966_Antonioni_-_Blow_Up",
    "1966_Bergman_-_Persona",
    "1966_Godard_-_Made_in_USA",
    "1966_Godard_-_Masculin_feminin",
    "1967_Godard_-_2_ou_3_choses_que_je_sais_d_elle",
    "1967_Godard_-_La_chinoise",
    "1967_Godard_-_Weekend",
    "1967_Scorsese_-_Who_s_that_knocking_on_my_door",
    "1968_Bergman_-_Skammen",
    "1968_Bergman_-_Vargtimmen",
    "1969_Bergman_-_En_Passion",
    "1969_Bergman_-_Riten",
    "1969_Fellini_-_Satyricon",
    "1969_Godard_-_Le_gai_savoir",
    "1970_Antonioni_-_Zabriskie_point",
    "1971_Bergman_-_Beroringen",
    "1972_Bergman_-_Viskningar_och_rop",
    "1972_Fellini_-_Roma",
    "1972_Godard_-_Tout_va_Bien",
    "1972_Scorsese_-_Boxcar_Bertha",
    "1973_Fellini_-_Amarcord",
    "1973_Scorsese_-_Mean_Streets",
    "1974_Scorsese_-_Alice_Doesn_t_Live_Here_Anymore",
    "1976_Fellini_-_Il_Casanova_di_Federico_Fellini",
    "1976_Scorsese_-_Taxi_Driver",
    "1977_Bergman_-_Das_Schlangenei",
    "1977_Scorsese_-_New_York_New_York",
    "1977_Tarr_-_Csaladi_tuzfeszek",
    "1978_Bergman_-_Hostsonaten",
    "1978_Fellini_-_Prova_d_orchestra",
    "1980_Bergman_-_Aus_dem_Leben_der_Marionetten",
    "1980_Scorsese_-_Raging_Bull",
    "1981_Tarr_-_Szabadgyalog",
    "1982_Antonioni_-_Identificazione_di_una_donna",
    "1982_Bergman_-_Fanny_es_Alexander",
    "1982_Tarr_-_Macbeth",
    "1982_Tarr_-_Panelkapcsolat",
    "1983_Fellini_-_E_la_nave_va",
    "1983_Godard_-_Prenom_Carmen",
    "1985_Godard_-_Detective",
    "1985_Godard_-_Je_vous_salue_Marie",
    "1985_Scorsese_-_After_Hours",
    "1985_Tarr_-_Oszi_almanach",
    "1986_Fellini_-_Ginger_e_Fred",
    "1987_Godard_-_King_Lear",
    "1987_Godard_-_Soigne_ta_droite",
    "1988_Scorsese_-_The_last_temptation_of_christ",
    "1988_Tarr_-_Karhozat",
    "1990_Fellini_-_La_voce_della_luna",
    "1990_Godard_-_Nouvelle_Vague",
    "1990_Scorsese_-_Goodfellas",
    "1991_Godard_-_Allemagne_annee_90_neuf_zero",
    "1991_Scorsese_-_Cape_Fear",
    "1994_Tarr_-_Satatango",
    "1995_Scorsese_-_Casino",
    "1996_Godard_-_For_Ever_Mozart",
    "1997_Scorsese_-_Kundun",
    "2001_Godard_-_Eloge_de_l_amour",
    "2002_Scorsese_-_Gangs_of_New_York",
    "2003_Bergman_-_Saraband",
    "2004_Godard_-_Notre_musique",
    "2004_Scorsese_-_The_Aviator",
    "2006_Scorsese_-_The_Departed",
    "2007_Tarr_-_A_Londoni_Ferfi",
    "2007_Tarr_-_A_Torinoi_lo",
    "2010_Godard_-_Film_socialisme",
    "2010_Scorsese_-_Shutter_Island",
    "2011_Scorsese_-_Hugo",
    "2013_Scorsese_-_The_Wolf_of_Wall_Street",
]

OUTPUT_IMAGE_SIZE = 224
DEFAULT_OUTPUT_NAME = "shotscale"
